import { fetchPlats, fetchGames, fetchGame } from './firebaseConnect';

export const getGames = async (searchTerm, platformID) => {
    try{
      const games = await fetchGames({platformID: platformID, searchTerm: searchTerm});
      return games.data;
    } catch(error){
      throw new Error(error.message);
    }

}

export const getPlatforms = async () => {
    try{
      const platforms = await fetchPlats('');
      return platforms.data;
    } catch (error){
      // error is an https error generated by Firebase.
      // it has property name: firebase

      // possibly throw a custom error of http type so status code can be checked in components?
      throw new Error(error.message);
    }
}

export const getGame = async (searchTerm) => {
  try{
    const game = await fetchGame({searchTerm: searchTerm});
    return game.data[0];
  } catch(error){
    throw new Error(error.message);
  }
}